FROM anapsix/alpine-java

COPY target/spring-boot-kubernetes-engine-0.0.1-SNAPSHOT.jar /home/spring-boot-kubernetes-engine-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "/home/spring-boot-kubernetes-engine-0.0.1-SNAPSHOT.jar"]